# Generated by Django 3.2.6 on 2021-08-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
